services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    WechatWorkContactWayBundle\DataFixtures\:
        resource: '../../DataFixtures/'
        tags: ['doctrine.fixture.orm']